
package tn.esprit.ejb;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "scolaritePorType", targetNamespace = "http://ejb.esprit.tn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScolaritePorType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "etat", targetNamespace = "")
    @RequestWrapper(localName = "getEtatInscription", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.GetEtatInscription")
    @ResponseWrapper(localName = "getEtatInscriptionResponse", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.GetEtatInscriptionResponse")
    public String getEtatInscription();

    /**
     * 
     * @param dateNaissance
     * @param adresse
     * @param cin
     * @param nom
     * @param prenom
     * @param numTel
     * @param email
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "numeroConfirmation", targetNamespace = "")
    @RequestWrapper(localName = "inscrire", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.Inscrire")
    @ResponseWrapper(localName = "inscrireResponse", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.InscrireResponse")
    public int inscrire(
        @WebParam(name = "cin", targetNamespace = "")
        String cin,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "dateNaissance", targetNamespace = "")
        String dateNaissance,
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse,
        @WebParam(name = "numTel", targetNamespace = "")
        long numTel,
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param numInscription
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(name = "fraisInscription", targetNamespace = "")
    @RequestWrapper(localName = "calculerFraisInscription", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.CalculerFraisInscription")
    @ResponseWrapper(localName = "calculerFraisInscriptionResponse", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.CalculerFraisInscriptionResponse")
    public float calculerFraisInscription(
        @WebParam(name = "numInscription", targetNamespace = "")
        int numInscription);

    /**
     * 
     * @param numInscription
     * @return
     *     returns tn.esprit.ejb.Etudiant
     */
    @WebMethod
    @WebResult(name = "infoEtudiant", targetNamespace = "")
    @RequestWrapper(localName = "getInfoEtudiant", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.GetInfoEtudiant")
    @ResponseWrapper(localName = "getInfoEtudiantResponse", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.GetInfoEtudiantResponse")
    public Etudiant getInfoEtudiant(
        @WebParam(name = "numInscription", targetNamespace = "")
        int numInscription);

    /**
     * 
     * @return
     *     returns java.util.List<tn.esprit.ejb.Etudiant>
     */
    @WebMethod
    @WebResult(name = "etudiant", targetNamespace = "")
    @RequestWrapper(localName = "getListEtudiant", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.GetListEtudiant")
    @ResponseWrapper(localName = "getListEtudiantResponse", targetNamespace = "http://ejb.esprit.tn/", className = "tn.esprit.ejb.GetListEtudiantResponse")
    public List<Etudiant> getListEtudiant();

}
